require('../src/db/init');
const fs = require('fs'); const path = require('path'); const crypto = require('crypto'); const sharp = require('sharp');
const db = require('../src/db/database'); const env = require('../src/config/env'); const { sha256File, signRecord } = require('../src/services/integrity.service');
fs.mkdirSync(env.uploadDir,{recursive:true});
const actors=db.prepare("SELECT id,email FROM users WHERE email IN ('officer1@chromora.local','officer2@chromora.local')").all();
const scenarios=[['DEMO-01','NEGATIVE','ACCEPTABLE'],['DEMO-02','POSITIVE','ACCEPTABLE'],['DEMO-03','INCONCLUSIVE','ACCEPTABLE'],['DEMO-04','POSITIVE','ACCEPTABLE'],['DEMO-05','NEGATIVE','ACCEPTABLE'],['DEMO-06','ANALYSIS_PENDING','ACCEPTABLE'],['DEMO-07','INCONCLUSIVE','REVIEW_RECOMMENDED'],['DEMO-08','NEGATIVE','ACCEPTABLE'],['DEMO-09','POSITIVE','ACCEPTABLE'],['DEMO-10','NEGATIVE','ACCEPTABLE'],['DEMO-11','POSITIVE','ACCEPTABLE'],['DEMO-12','INCONCLUSIVE','ACCEPTABLE']];
function svg(label,index){const swatches=['#C9D7E7','#A78BFA','#22C7E8','#F59E0B','#22C55E','#EF4444'];return `<svg width="1200" height="800" xmlns="http://www.w3.org/2000/svg"><rect width="1200" height="800" fill="#e7edf3"/><rect x="70" y="70" width="1060" height="660" rx="30" fill="#ffffff" stroke="#24344D" stroke-width="8"/><text x="110" y="135" font-family="Arial" font-size="36" fill="#142238">CHROMORA DEMO — ${label}</text><text x="110" y="690" font-family="Arial" font-size="28" fill="#EF4444">NOT FORENSIC EVIDENCE · SYNTHETIC UI DEMONSTRATION</text><rect x="120" y="210" width="550" height="220" rx="18" fill="#dfe7ef" stroke="#24344D" stroke-width="5"/><rect x="170" y="270" width="450" height="90" rx="15" fill="${swatches[index%swatches.length]}"/><text x="120" y="490" font-family="Arial" font-size="25" fill="#142238">ABSTRACT REACTION REGION — NOT A DRUG MAPPING</text>${swatches.map((c,i)=>`<rect x="760" y="${190+i*65}" width="250" height="48" rx="7" fill="${c}"/>`).join('')}<text x="760" y="160" font-family="Arial" font-size="24" fill="#142238">DEMO REFERENCE PATCHES</text></svg>`;}
(async()=>{for(let i=0;i<scenarios.length;i++){const [scenario,result,quality]=scenarios[i];if(db.prepare('SELECT id FROM test_records WHERE demo_scenario=?').get(scenario))continue;const actor=actors[i%actors.length];const id=crypto.randomUUID();const number=`FT-DEMO-${String(i+1).padStart(2,'0')}`;const file=path.join(env.uploadDir,`${id}.png`);await sharp(Buffer.from(svg(scenario,i))).png().toFile(file);const capturedAt=new Date(Date.now()-(i%7)*86400000-(i*3600000)).toISOString();const stored=path.relative(env.rootDir,file).replace(/\\/g,'/');db.prepare('INSERT INTO test_records (id,test_number,test_profile,operator_id,captured_at,latitude,longitude,location_accuracy,original_image_path,image_sha256,capture_quality,reference_card_status,presumptive_result,analysis_source,data_origin,demo_scenario,signed_payload_version,integrity_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,number,'DEMO_COLORIMETRIC_A',actor.id,capturedAt,28.6100+i*.001,77.2090+i*.001,8+i,stored,sha256File(file),quality,'NOT_IMPLEMENTED',result,'DEMO_SEED','DEMO_SEED',scenario,1,'PENDING');let record=db.prepare('SELECT * FROM test_records WHERE id=?').get(id);const signed=signRecord(record);db.prepare('UPDATE test_records SET record_signature=?,signature_algorithm=?,integrity_status=? WHERE id=?').run(signed.signature,signed.algorithm,'VERIFIED',id);db.prepare('INSERT INTO audit_logs (id,actor_user_id,test_record_id,action,metadata_json) VALUES (?,?,?,?,?)').run(crypto.randomUUID(),actor.id,id,'DEMO_RECORD_SEEDED',JSON.stringify({scenario,dataOrigin:'DEMO_SEED'}));if(scenario==='DEMO-12'){fs.appendFileSync(file,'\nTAMPERED AFTER SIGNING');db.prepare("UPDATE test_records SET integrity_status='PENDING' WHERE id=?").run(id);}}
console.log('Chromora demo seed complete. Records are synthetic DEMO_SEED data only.');})();
