const express = require('express');
const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const path = require('path');
const fs = require('fs');
const jwt = require('jsonwebtoken');
const multer = require('multer');
const sharp = require('sharp');
const { z } = require('zod');
const db = require('../db/database');
const env = require('../config/env');
const { requireAuth, roles, currentUser } = require('../middleware/auth');
const { AppError } = require('../utils/http');
const { sha256File, signRecord, verifyRecord } = require('../services/integrity.service');
const { generateFieldTestReport } = require('../services/reportGenerator');

const router = express.Router();
const asyncHandler = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
const audit = (action, actor, record = null, metadata = null) => db.prepare('INSERT INTO audit_logs (id,actor_user_id,test_record_id,action,metadata_json) VALUES (?,?,?,?,?)').run(crypto.randomUUID(), actor, record, action, metadata ? JSON.stringify(metadata) : null);
const MASTER_ADMIN_EMAIL = 'admin@chromora.local';
const USER_ROLES = ['MASTER_ADMIN','ADMIN','FIELD_OFFICER'];
const ACCOUNT_STATUSES = ['PENDING_APPROVAL','APPROVED','REJECTED','SUSPENDED'];
const safeUser = user => ({ id: user.id, fullName: user.full_name, email: user.email, phone: user.phone, role: user.role, requestedRole: user.requested_role, accountStatus: user.account_status, employeeId: user.employee_id, department: user.department, designation: user.designation, jurisdictionRegion: user.jurisdiction_region, registeredAt: user.registered_at, approvedAt: user.approved_at, rejectedAt: user.rejected_at });
const userById = id => db.prepare('SELECT * FROM users WHERE id=?').get(id);
const isMasterAdmin = user => user && String(user.email).toLowerCase() === MASTER_ADMIN_EMAIL;
const protectMaster = user => { if (isMasterAdmin(user) || user?.role==='MASTER_ADMIN') throw new AppError(403, 'The Master Admin account cannot be changed.'); return user; };
const generatedEmployeeId = () => `CHR-USER-${new Date().getFullYear()}-${String(db.prepare("SELECT count(*) count FROM users WHERE employee_id LIKE 'CHR-USER-%'").get().count + 1).padStart(4,'0')}`;
const recordWithOperator = id => db.prepare('SELECT t.*, u.full_name operator_name, u.email operator_email, u.employee_id operator_employee_id FROM test_records t JOIN users u ON u.id=t.operator_id WHERE t.id=?').get(id);
const imagePathFor = record => path.resolve(env.rootDir, record.original_image_path || '');
const usableEvidencePath = record => { const file = imagePathFor(record); const root = path.resolve(env.uploadDir); if (!record.original_image_path || path.relative(root, file).startsWith('..') || !fs.existsSync(file)) throw new AppError(404, 'Evidence image unavailable.'); return file; };
const canAccess = (req, record) => ['ADMIN','MASTER_ADMIN'].includes(req.user.role) || record.operator_id === req.user.sub;
const requireRecordAccess = (req, record) => { if (!record) throw new AppError(404, 'Test record not found.'); if (!canAccess(req, record)) throw new AppError(403, 'You do not have permission to access this field test.'); return record; };
const reSign = (id, actor, action) => { const record = recordWithOperator(id); if (!record.image_sha256) return record; const signed = signRecord(record); db.prepare('UPDATE test_records SET record_signature=?,signature_algorithm=?,signed_payload_version=?,integrity_status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(signed.signature,signed.algorithm,signed.signedPayloadVersion,'VERIFIED',id); audit(action,actor,id,{ signedPayloadVersion:signed.signedPayloadVersion }); return recordWithOperator(id); };

router.post('/auth/login', asyncHandler((req, res) => {
  const input = z.object({ email: z.string().email(), password: z.string().min(1), application: z.enum(['WEB', 'MOBILE']) }).parse(req.body);
  const user = db.prepare('SELECT * FROM users WHERE lower(email)=lower(?)').get(input.email);
  if (!user || !bcrypt.compareSync(input.password, user.password_hash)) throw new AppError(401, 'Invalid email or password.');
  if (user.account_status !== 'APPROVED') { const messages={PENDING_APPROVAL:'Your registration is pending approval.',REJECTED:'Your registration was rejected.',SUSPENDED:'Your account has been suspended.'}; throw new AppError(403,messages[user.account_status]||'Your account is not approved for access.'); }
  const allowed = input.application === 'WEB' ? ['MASTER_ADMIN','ADMIN'] : ['FIELD_OFFICER'];
  if (!allowed.includes(user.role)) throw new AppError(403, input.application === 'WEB' ? 'Field Officer accounts must use the Chromora mobile companion.' : 'Administrator accounts must use the Chromora Web Command Centre.');
  const token = jwt.sign({ sub: user.id, role: user.role, application: input.application }, env.jwtSecret, { expiresIn: '8h' });
  audit('LOGIN_SUCCESS', user.id);
  res.json({ token, user: safeUser(user) });
}));
router.get('/auth/me', requireAuth, (req, res) => res.json({ user: safeUser(currentUser(req)) }));
router.post('/auth/register', asyncHandler((req,res)=>{const input=z.object({fullName:z.string().trim().min(2).max(120),officialEmail:z.string().trim().email(),phone:z.string().trim().min(5).max(40),department:z.string().trim().min(2).max(160),designation:z.string().trim().min(2).max(160),requestedRole:z.enum(['ADMIN','FIELD_OFFICER']),jurisdictionRegion:z.string().trim().max(160).optional(),password:z.string().min(8).max(200),confirmPassword:z.string().min(8).max(200)}).superRefine((value,ctx)=>{if(value.password!==value.confirmPassword)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Passwords do not match.',path:['confirmPassword']});if(value.requestedRole==='FIELD_OFFICER'&&!value.jurisdictionRegion)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Jurisdiction or region is required for Field Officers.',path:['jurisdictionRegion']});}).parse(req.body);if(db.prepare('SELECT id FROM users WHERE lower(email)=lower(?)').get(input.officialEmail))throw new AppError(409,'An account with this official email already exists.');const id=crypto.randomUUID(),employeeId=generatedEmployeeId();db.prepare('INSERT INTO users (id,full_name,email,password_hash,role,requested_role,account_status,employee_id,phone,department,designation,jurisdiction_region,registered_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)').run(id,input.fullName,input.officialEmail,bcrypt.hashSync(input.password,12),input.requestedRole,input.requestedRole,'PENDING_APPROVAL',employeeId,input.phone,input.department,input.designation,input.requestedRole==='FIELD_OFFICER'?input.jurisdictionRegion:null);const user=userById(id);audit('USER_REGISTERED',null,null,{userId:id,employeeId,requestedRole:input.requestedRole});res.status(201).json({user:safeUser(user),message:'Registration submitted for approval.'});}));

fs.mkdirSync(env.uploadDir, { recursive: true });
const upload = multer({
  storage: multer.diskStorage({ destination: env.uploadDir, filename: (req, file, done) => done(null, `${crypto.randomUUID()}${path.extname(file.originalname).toLowerCase()}`) }),
  limits: { fileSize: 10 * 1024 * 1024 },
  fileFilter: (req, file, done) => /^image\/(jpeg|png|webp)$/.test(file.mimetype) ? done(null, true) : done(new AppError(400, 'Only JPEG, PNG, and WebP evidence images are supported.'))
});

router.get('/test-profiles', requireAuth, (req, res) => res.json({ profiles: db.prepare('SELECT code, display_name, status, description FROM test_profiles ORDER BY display_name').all() }));
router.get('/search', requireAuth, roles('ADMIN', 'MASTER_ADMIN'), (req, res) => { const q=String(req.query.q||'').trim(); if(q.length<2)return res.json({fieldTests:[],operators:[],locations:[]}); const like=`%${q}%`; const fieldTests=db.prepare(`SELECT t.id,t.test_number,t.location_label,t.presumptive_result,u.full_name operator_name FROM test_records t JOIN users u ON u.id=t.operator_id WHERE t.workflow_status!='DRAFT' AND (t.test_number LIKE ? OR t.location_label LIKE ? OR u.full_name LIKE ?) ORDER BY t.captured_at DESC LIMIT 5`).all(like,like,like).map(x=>({kind:'FIELD TEST',id:x.id,label:x.test_number,detail:`${x.operator_name} · ${x.location_label||'No location'} · ${x.presumptive_result.replaceAll('_',' ')}`})); const operators=db.prepare(`SELECT full_name,email,employee_id FROM users WHERE full_name LIKE ? OR email LIKE ? OR employee_id LIKE ? LIMIT 5`).all(like,like,like).map(x=>({kind:'OPERATOR',label:x.full_name,detail:[x.email,x.employee_id].filter(Boolean).join(' · '),to:`/operators?search=${encodeURIComponent(x.full_name)}`})); const locations=db.prepare(`SELECT location_label label,count(*) count FROM test_records WHERE workflow_status!='DRAFT' AND location_label IS NOT NULL AND location_label LIKE ? GROUP BY location_label LIMIT 5`).all(like).map(x=>({kind:'LOCATION',label:x.label,detail:`${x.count} field tests`,to:`/map?location=${encodeURIComponent(x.label)}`})); res.json({fieldTests,operators,locations}); });
router.get('/dashboard', requireAuth, roles('ADMIN', 'MASTER_ADMIN'), (req, res) => {
  const range = [1, 7, 30, 90].includes(Number(req.query.range)) ? Number(req.query.range) : 7;
  const since = new Date(Date.now() - range * 86400000).toISOString();
  const summary = db.prepare(`SELECT count(*) totalTests, sum(presumptive_result='POSITIVE') positive, sum(presumptive_result='NEGATIVE') negative, sum(presumptive_result='INCONCLUSIVE') inconclusive, sum(presumptive_result='ANALYSIS_PENDING') analysisPending, sum(integrity_status='VERIFIED') integrityVerified, sum(integrity_status='PENDING') integrityPending, sum(integrity_status='HASH_MISMATCH') hashMismatch, sum(integrity_status='SIGNATURE_INVALID') signatureInvalid, sum(integrity_status IN ('HASH_MISMATCH','SIGNATURE_INVALID')) integrityIssues FROM test_records WHERE workflow_status!='DRAFT' AND captured_at>=?`).get(since);
  const byResult = db.prepare(`SELECT presumptive_result result, count(*) count FROM test_records WHERE workflow_status!='DRAFT' AND captured_at>=? GROUP BY presumptive_result`).all(since);
  const locations = db.prepare(`SELECT t.id,t.test_number,t.latitude,t.longitude,t.location_label,t.location_accuracy,t.captured_at,t.presumptive_result,t.integrity_status,u.full_name operator_name FROM test_records t JOIN users u ON u.id=t.operator_id WHERE t.workflow_status!='DRAFT' AND t.captured_at>=? AND t.latitude IS NOT NULL AND t.longitude IS NOT NULL ORDER BY t.captured_at DESC`).all(since);
  const recent = db.prepare(`SELECT t.id,t.test_number,t.location_label,t.latitude,t.longitude,t.presumptive_result,t.integrity_status,t.data_origin,t.demo_scenario,t.captured_at,u.full_name operator_name FROM test_records t JOIN users u ON u.id=t.operator_id WHERE t.workflow_status!='DRAFT' AND t.captured_at>=? ORDER BY t.captured_at DESC LIMIT 3`).all(since);
  const bucketDays = Math.min(range, 30); const dailyActivity = db.prepare(`WITH RECURSIVE days(day) AS (SELECT date('now','-${bucketDays - 1} days') UNION ALL SELECT date(day,'+1 day') FROM days WHERE day < date('now')) SELECT day date, count(t.id) count FROM days LEFT JOIN test_records t ON date(t.captured_at)=day AND t.workflow_status!='DRAFT' AND t.captured_at>=? GROUP BY day ORDER BY day`).all(since);
  const demoActive = db.prepare("SELECT count(*) count FROM test_records WHERE workflow_status!='DRAFT' AND data_origin='DEMO_SEED'").get().count > 0;
  res.json({ range, summary: { ...summary, totalRecords: summary.totalTests, integrityTotal: summary.totalTests }, byResult, locations, recent, dailyActivity, demoActive });
});

router.get('/test-records', requireAuth, asyncHandler((req, res) => {
  const params=[]; let where="WHERE t.workflow_status!='DRAFT' AND (t.test_number LIKE ? OR u.full_name LIKE ? OR coalesce(t.location_label,'') LIKE ?)"; const search=`%${String(req.query.search||'').trim()}%`; params.push(search,search,search);
  if (req.user.role === 'FIELD_OFFICER') { where+=' AND t.operator_id=?'; params.push(req.user.sub); }
  for (const [field,key] of [['t.presumptive_result','result'],['t.integrity_status','integrity'],['t.data_origin','origin']]) if (req.query[key] && req.query[key] !== 'ALL') { where+=` AND ${field}=?`; params.push(req.query[key]); }
  if ([1,7,30,90].includes(Number(req.query.range))) { where+=' AND t.captured_at>=?'; params.push(new Date(Date.now()-Number(req.query.range)*86400000).toISOString()); } if (req.query.from) { where+=' AND date(t.captured_at)>=date(?)'; params.push(req.query.from); } if (req.query.to) { where+=' AND date(t.captured_at)<=date(?)'; params.push(req.query.to); }
  const records=db.prepare(`SELECT t.*,u.full_name operator_name FROM test_records t JOIN users u ON u.id=t.operator_id ${where} ORDER BY t.captured_at DESC`).all(...params); res.json({records});
}));
router.get('/test-records/:id', requireAuth, asyncHandler((req, res) => {
  const record = requireRecordAccess(req, recordWithOperator(req.params.id));
  res.json({ record });
}));
router.get('/test-records/:id/potential-issues', requireAuth, roles('ADMIN', 'MASTER_ADMIN'), asyncHandler((req, res) => { const record=requireRecordAccess(req,recordWithOperator(req.params.id)); const issues=[]; const add=(code,title,description,severity)=>issues.push({code,title,description,severity}); if(!record.original_image_path||!fs.existsSync(imagePathFor(record)))add('NO_EVIDENCE','No evidence image','No evidence image is available for this field-test record.','WARNING'); if(record.latitude==null||record.longitude==null)add('GPS_NOT_CAPTURED','Location not captured','No GPS coordinates were recorded for this field-test record.','WARNING'); if(record.capture_quality==='REVIEW_RECOMMENDED')add('CAPTURE_REVIEW_RECOMMENDED','Capture requires review','The stored image dimensions require operational review.','WARNING'); if(record.integrity_status==='PENDING')add('INTEGRITY_PENDING','Integrity verification pending','Evidence integrity has not yet been verified.','INFO'); if(record.integrity_status==='HASH_MISMATCH')add('HASH_MISMATCH','Evidence hash mismatch','The current evidence file no longer matches its stored SHA-256 fingerprint.','CRITICAL'); if(record.integrity_status==='SIGNATURE_INVALID')add('SIGNATURE_INVALID','Record signature invalid','The signed record fields no longer validate against the stored signature.','CRITICAL'); if(record.presumptive_result==='ANALYSIS_PENDING')add('ANALYSIS_PENDING','Analysis pending','The current record remains in an analysis-pending state.','INFO'); res.json({issues,count:issues.length}); }));
router.post('/test-records/:id/lab-review', requireAuth, roles('ADMIN', 'MASTER_ADMIN'), asyncHandler((req,res)=>{const note=String(req.body?.note||'').trim();if(note.length>1000)throw new AppError(400,'Review note must be 1000 characters or fewer.');const record=requireRecordAccess(req,recordWithOperator(req.params.id));if(record.lab_review_status==='REQUESTED')throw new AppError(409,'Lab review has already been requested for this record.');db.prepare("UPDATE test_records SET lab_review_status='REQUESTED',lab_review_requested_at=CURRENT_TIMESTAMP,lab_review_requested_by=?,lab_review_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(req.user.sub,note||null,record.id);audit('LAB_REVIEW_REQUESTED',req.user.sub,record.id,{testNumber:record.test_number,note:note||null});res.json({record:recordWithOperator(record.id)}); }));
router.post('/test-records', requireAuth, roles('FIELD_OFFICER', 'ADMIN', 'MASTER_ADMIN'), asyncHandler((req, res) => {
  const data = z.object({
    testProfile: z.string().trim().max(120).optional(), notes: z.string().trim().max(1000).optional(),
    capturedAt: z.string().datetime().optional(), latitude: z.number().min(-90).max(90).nullable().optional(),
    longitude: z.number().min(-180).max(180).nullable().optional(), locationAccuracy: z.number().nonnegative().nullable().optional(), draft: z.boolean().optional()
  }).parse(req.body);
  const id = crypto.randomUUID();
  const testNumber = `FT-${new Date().getFullYear()}-${String(db.prepare('SELECT count(*) count FROM test_records').get().count + 1).padStart(4, '0')}`;
  const workflowStatus=data.draft?'DRAFT':'ACTIVE';
  db.prepare('INSERT INTO test_records (id,test_number,test_profile,operator_id,notes,captured_at,latitude,longitude,location_accuracy,workflow_status) VALUES (?,?,?,?,?,?,?,?,?,?)')
    .run(id, testNumber, data.testProfile || null, req.user.sub, data.notes || null, data.capturedAt || new Date().toISOString(), data.latitude ?? null, data.longitude ?? null, data.locationAccuracy ?? null, workflowStatus);
  if(workflowStatus==='ACTIVE')audit('FIELD_TEST_STARTED', req.user.sub, id, { locationCaptured: data.latitude != null && data.longitude != null });
  res.status(201).json({ record: recordWithOperator(id) });
}));
router.delete('/test-records/:id/draft', requireAuth, roles('FIELD_OFFICER', 'ADMIN', 'MASTER_ADMIN'), asyncHandler((req,res)=>{const record=requireRecordAccess(req,recordWithOperator(req.params.id));if(record.workflow_status!=='DRAFT')throw new AppError(409,'Only an unsubmitted field-test draft can be discarded.');if(record.original_image_path){const file=imagePathFor(record);if(fs.existsSync(file))fs.rmSync(file,{force:true});}db.prepare('DELETE FROM audit_logs WHERE test_record_id=?').run(record.id);db.prepare('DELETE FROM test_records WHERE id=?').run(record.id);res.json({deleted:true});}));
router.post('/test-records/:id/complete-workflow', requireAuth, roles('FIELD_OFFICER', 'ADMIN', 'MASTER_ADMIN'), asyncHandler((req,res)=>{const record=requireRecordAccess(req,recordWithOperator(req.params.id));if(record.workflow_status==='DRAFT'){if(!record.original_image_path)throw new AppError(409,'Evidence must be uploaded before completing the workflow.');db.prepare("UPDATE test_records SET workflow_status='ACTIVE',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(record.id);audit('FIELD_TEST_STARTED',req.user.sub,record.id,{locationCaptured:record.latitude!=null&&record.longitude!=null});}res.json({record:recordWithOperator(record.id)});}));
router.post('/test-records/:id/report', requireAuth, roles('ADMIN', 'MASTER_ADMIN'), asyncHandler(async (req,res)=>{ const record=requireRecordAccess(req,recordWithOperator(req.params.id)); if(record.workflow_status==='DRAFT')throw new AppError(409,'A draft field test cannot generate a report.'); const existing=db.prepare('SELECT * FROM reports WHERE test_record_id=?').get(record.id); const reportId=existing?.id||crypto.randomUUID(); const relative=`uploads/reports/${reportId}.pdf`; const output=path.resolve(env.rootDir,relative); const issues=[]; if(!record.original_image_path||!fs.existsSync(imagePathFor(record)))issues.push({severity:'WARNING',title:'No evidence image',description:'No evidence image is available for this field-test record.'}); if(record.latitude==null||record.longitude==null)issues.push({severity:'WARNING',title:'Location not captured',description:'No GPS coordinates were recorded for this field-test record.'}); if(record.integrity_status==='HASH_MISMATCH')issues.push({severity:'CRITICAL',title:'Evidence hash mismatch',description:'Evidence no longer matches its stored SHA-256 fingerprint.'}); if(record.integrity_status==='SIGNATURE_INVALID')issues.push({severity:'CRITICAL',title:'Record signature invalid',description:'Signed fields no longer validate.'}); if(record.integrity_status==='PENDING')issues.push({severity:'INFO',title:'Integrity verification pending',description:'Evidence integrity has not yet been verified.'}); if(record.presumptive_result==='ANALYSIS_PENDING')issues.push({severity:'INFO',title:'Analysis pending',description:'The record remains in an analysis-pending state.'}); const reportRecord={...record,original_image_path:record.original_image_path?imagePathFor(record):null}; await generateFieldTestReport({record:reportRecord,potentialIssues:issues,outputPath:output}); if(existing)db.prepare('UPDATE reports SET file_path=?,generated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(relative,req.user.sub,reportId); else db.prepare('INSERT INTO reports (id,test_record_id,file_path,generated_by) VALUES (?,?,?,?)').run(reportId,record.id,relative,req.user.sub); audit(existing?'REPORT_REGENERATED':'REPORT_GENERATED',req.user.sub,record.id,{reportId,testRecordId:record.id,testNumber:record.test_number}); const report=db.prepare('SELECT id,test_record_id,generated_at,updated_at FROM reports WHERE id=?').get(reportId); res.json({report:{...report,test_number:record.test_number}}); }));
const reportWithDetails = id => db.prepare(`SELECT r.id,r.test_record_id,r.generated_at,r.updated_at,r.generated_by,t.test_number,t.presumptive_result,t.integrity_status,t.lab_review_status,u.full_name operator_name,g.full_name generated_by_name FROM reports r JOIN test_records t ON t.id=r.test_record_id JOIN users u ON u.id=t.operator_id LEFT JOIN users g ON g.id=r.generated_by WHERE r.id=? AND t.workflow_status!='DRAFT'`).get(id);
const reportFile = report => { const row=db.prepare('SELECT file_path FROM reports WHERE id=?').get(report.id); const file=path.resolve(env.rootDir,row?.file_path||''); if(!row||path.relative(path.resolve(env.reportDir),file).startsWith('..'))throw new AppError(404,'Report not found.'); if(!fs.existsSync(file))throw new AppError(404,'Generated report file is unavailable.'); return file; };
router.get('/reports', requireAuth, roles('ADMIN','MASTER_ADMIN'), (req,res)=>{const q=`%${String(req.query.search||'').trim()}%`;const params=[q,q];let where="WHERE t.workflow_status!='DRAFT' AND (t.test_number LIKE ? OR u.full_name LIKE ?)";if(req.query.result){where+=' AND t.presumptive_result=?';params.push(req.query.result);}const reports=db.prepare(`SELECT r.id,r.test_record_id,r.generated_at,r.updated_at,r.generated_by,t.test_number,t.presumptive_result,u.full_name operator_name,g.full_name generated_by_name FROM reports r JOIN test_records t ON t.id=r.test_record_id JOIN users u ON u.id=t.operator_id LEFT JOIN users g ON g.id=r.generated_by ${where} ORDER BY r.updated_at DESC`).all(...params);res.json({reports});});
router.get('/reports/:id', requireAuth, roles('ADMIN','MASTER_ADMIN'), asyncHandler((req,res)=>{const report=reportWithDetails(req.params.id);if(!report)throw new AppError(404,'Report not found.');res.json({report});}));
router.get('/reports/:id/file', requireAuth, roles('ADMIN','MASTER_ADMIN'), asyncHandler((req,res)=>{const report=reportWithDetails(req.params.id);if(!report)throw new AppError(404,'Report not found.');const name=`Chromora_${report.test_number}_Report.pdf`;res.type('application/pdf').set('Content-Disposition',`inline; filename="${name}"`).sendFile(reportFile(report));}));
router.get('/reports/:id/download', requireAuth, roles('ADMIN','MASTER_ADMIN'), asyncHandler((req,res)=>{const report=reportWithDetails(req.params.id);if(!report)throw new AppError(404,'Report not found.');res.download(reportFile(report),`Chromora_${report.test_number}_Report.pdf`);}));
router.delete('/reports/:id', requireAuth, roles('ADMIN','MASTER_ADMIN'), asyncHandler((req,res)=>{const report=reportWithDetails(req.params.id);if(!report)throw new AppError(404,'Report not found.');const row=db.prepare('SELECT file_path FROM reports WHERE id=?').get(report.id);const file=path.resolve(env.rootDir,row.file_path);if(file.startsWith(path.resolve(env.reportDir))&&fs.existsSync(file))fs.rmSync(file,{force:true});db.prepare('DELETE FROM reports WHERE id=?').run(report.id);audit('REPORT_DELETED',req.user.sub,report.test_record_id,{reportId:report.id,testRecordId:report.test_record_id,testNumber:report.test_number});res.json({deleted:true});}));
router.post('/test-records/:id/evidence', requireAuth, roles('FIELD_OFFICER', 'ADMIN', 'MASTER_ADMIN'), upload.single('image'), asyncHandler(async (req, res) => {
  const record = requireRecordAccess(req, recordWithOperator(req.params.id));
  if (!req.file) throw new AppError(400, 'An evidence image is required.');
  const metadata = await sharp(req.file.path).metadata();
  const quality = metadata.width >= 800 && metadata.height >= 600 ? 'ACCEPTABLE' : 'REVIEW_RECOMMENDED';
  const relativePath = path.relative(env.rootDir, req.file.path).replace(/\\/g, '/');
  const imageHash = sha256File(req.file.path);
  db.prepare('UPDATE test_records SET original_image_path=?, image_sha256=?, capture_quality=?, integrity_status=?, updated_at=CURRENT_TIMESTAMP WHERE id=?').run(relativePath, imageHash, quality, 'PENDING', record.id);
  const reSigned = reSign(record.id, req.user.sub, 'TEST_EVIDENCE_HASHED_AND_SIGNED');
  audit('TEST_EVIDENCE_STORED', req.user.sub, record.id, { width: metadata.width, height: metadata.height, quality, hashAlgorithm: 'SHA-256', signatureAlgorithm: reSigned.signature_algorithm });
  res.json({ record: reSigned, imageQuality: { state: quality, message: quality === 'ACCEPTABLE' ? 'Basic image dimensions are acceptable.' : 'Image may be too small; a retake is recommended.' } });
}));
router.get('/test-records/:id/evidence', requireAuth, asyncHandler((req, res) => { const record = requireRecordAccess(req, recordWithOperator(req.params.id)); res.sendFile(usableEvidencePath(record)); }));
router.post('/test-records/:id/verify-integrity', requireAuth, asyncHandler((req, res) => {
  const record = requireRecordAccess(req, recordWithOperator(req.params.id));
  const verification = verifyRecord(record, usableEvidencePath(record));
  db.prepare('UPDATE test_records SET integrity_status=?, updated_at=CURRENT_TIMESTAMP WHERE id=?').run(verification.status, record.id);
  audit('EVIDENCE_INTEGRITY_VERIFIED', req.user.sub, record.id, { status: verification.status });
  res.json({ verification, record: recordWithOperator(record.id) });
}));
router.get('/test-records/:id/verification', requireAuth, asyncHandler((req, res) => {
  const record = requireRecordAccess(req, recordWithOperator(req.params.id));
  res.json({ verification: { testNumber: record.test_number, integrityStatus: record.integrity_status, imageSha256: record.image_sha256, signatureAlgorithm: record.signature_algorithm, verificationCode: `CHR:${record.id}` } });
}));
router.post('/test-records/:id/analyze', requireAuth, asyncHandler((req, res) => {
  const record = requireRecordAccess(req, recordWithOperator(req.params.id));
  const steps = [
    { key: 'IMAGE_QUALITY', state: record.capture_quality === 'ACCEPTABLE' ? 'COMPLETE' : record.capture_quality === 'REVIEW_RECOMMENDED' ? 'WARNING' : 'PENDING', detail: 'Basic capture dimensions checked.' },
    { key: 'REFERENCE_CARD', state: 'NOT_IMPLEMENTED', detail: 'Reference-card detection is not implemented.' },
    { key: 'COLOUR_CALIBRATION', state: 'NOT_IMPLEMENTED', detail: 'Colour calibration is not implemented.' },
    { key: 'REACTION_REGION', state: 'NOT_IMPLEMENTED', detail: 'Reaction-region extraction is not implemented.' },
    { key: 'CLASSIFICATION', state: 'NOT_IMPLEMENTED', detail: 'No presumptive classification is generated.' }
  ];
  db.prepare('UPDATE test_records SET last_analysis_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(record.id);
  audit('ANALYSIS_RERUN', req.user.sub, record.id, { testNumber: record.test_number, capabilityStates: steps.map(step=>({key:step.key,state:step.state})) });
  res.json({ record: recordWithOperator(record.id), steps });
}));
router.get('/users', requireAuth, roles('ADMIN', 'MASTER_ADMIN'), (req,res)=>{const status=String(req.query.status||'');const users=db.prepare(`SELECT u.id,u.full_name,u.email,u.phone,u.role,u.requested_role,u.account_status,u.employee_id,u.department,u.designation,u.jurisdiction_region,u.registered_at,u.approved_by,u.approved_at,u.rejected_by,u.rejected_at,u.approval_note,u.created_at,approver.full_name approved_by_name,rejector.full_name rejected_by_name FROM users u LEFT JOIN users approver ON approver.id=u.approved_by LEFT JOIN users rejector ON rejector.id=u.rejected_by ${ACCOUNT_STATUSES.includes(status)?'WHERE u.account_status=?':''} ORDER BY u.registered_at DESC,u.created_at DESC`).all(...(ACCOUNT_STATUSES.includes(status)?[status]:[]));res.json({users:users.map(user=>({...user,...safeUser(user)}))});});
const approvalInput = body => z.object({approvalNote:z.string().trim().max(1000).optional()}).parse(body);
const approvalTarget = (req,id) => {const target=userById(id);if(!target)throw new AppError(404,'User not found.');protectMaster(target);if(target.id===req.user.sub)throw new AppError(403,'You cannot approve or reject your own registration.');return target;};
router.post('/users/:id/approve', requireAuth, roles('ADMIN','MASTER_ADMIN'), asyncHandler((req,res)=>{const target=approvalTarget(req,req.params.id),input=approvalInput(req.body);if(target.account_status!=='PENDING_APPROVAL'&&target.account_status!=='REJECTED')throw new AppError(409,'Only pending or rejected registrations can be approved.');db.prepare("UPDATE users SET account_status='APPROVED',approved_by=?,approved_at=CURRENT_TIMESTAMP,rejected_by=NULL,rejected_at=NULL,approval_note=? WHERE id=?").run(req.user.sub,input.approvalNote||null,target.id);audit('USER_APPROVED',req.user.sub,null,{userId:target.id,employeeId:target.employee_id,approvalNote:input.approvalNote||null});res.json({user:safeUser(userById(target.id))});}));
router.post('/users/:id/reject', requireAuth, roles('ADMIN','MASTER_ADMIN'), asyncHandler((req,res)=>{const target=approvalTarget(req,req.params.id),input=approvalInput(req.body);if(target.account_status!=='PENDING_APPROVAL')throw new AppError(409,'Only pending registrations can be rejected.');db.prepare("UPDATE users SET account_status='REJECTED',rejected_by=?,rejected_at=CURRENT_TIMESTAMP,approval_note=? WHERE id=?").run(req.user.sub,input.approvalNote||null,target.id);audit('USER_REJECTED',req.user.sub,null,{userId:target.id,employeeId:target.employee_id,approvalNote:input.approvalNote||null});res.json({user:safeUser(userById(target.id))});}));
router.post('/users/:id/suspend', requireAuth, roles('ADMIN','MASTER_ADMIN'), asyncHandler((req,res)=>{const target=protectMaster(userById(req.params.id));if(!target)throw new AppError(404,'User not found.');if(target.account_status==='SUSPENDED')throw new AppError(409,'User is already suspended.');db.prepare("UPDATE users SET account_status='SUSPENDED' WHERE id=?").run(target.id);audit('USER_SUSPENDED',req.user.sub,null,{userId:target.id,employeeId:target.employee_id});res.json({user:safeUser(userById(target.id))});}));
router.post('/users/:id/reactivate', requireAuth, roles('ADMIN','MASTER_ADMIN'), asyncHandler((req,res)=>{const target=protectMaster(userById(req.params.id));if(!target)throw new AppError(404,'User not found.');if(target.account_status!=='SUSPENDED')throw new AppError(409,'Only suspended users can be reactivated.');db.prepare("UPDATE users SET account_status='APPROVED' WHERE id=?").run(target.id);audit('USER_REACTIVATED',req.user.sub,null,{userId:target.id,employeeId:target.employee_id});res.json({user:safeUser(userById(target.id))});}));
router.put('/users/:id', requireAuth, roles('MASTER_ADMIN'), asyncHandler((req,res)=>{const target=userById(req.params.id);if(!target)throw new AppError(404,'User not found.');protectMaster(target);if(target.id===req.user.sub)throw new AppError(403,'Master Admin can only edit another user account.');const input=z.object({fullName:z.string().trim().min(2).max(120).optional(),officialEmail:z.string().trim().email().optional(),phone:z.string().trim().min(5).max(40).optional(),department:z.string().trim().min(2).max(160).optional(),designation:z.string().trim().min(2).max(160).optional(),jurisdictionRegion:z.string().trim().max(160).nullable().optional(),role:z.enum(['ADMIN','FIELD_OFFICER']).optional()}).parse(req.body);if(input.officialEmail&&String(input.officialEmail).toLowerCase()!==String(target.email).toLowerCase()&&db.prepare('SELECT id FROM users WHERE lower(email)=lower(?)').get(input.officialEmail))throw new AppError(409,'An account with this official email already exists.');const next={fullName:input.fullName??target.full_name,email:input.officialEmail??target.email,phone:input.phone??target.phone,department:input.department??target.department,designation:input.designation??target.designation,jurisdiction:input.jurisdictionRegion??target.jurisdiction_region,role:input.role??target.role};db.prepare('UPDATE users SET full_name=?,email=?,phone=?,department=?,designation=?,jurisdiction_region=?,role=?,requested_role=? WHERE id=?').run(next.fullName,next.email,next.phone,next.department,next.designation,next.jurisdiction,next.role,next.role,target.id);audit('USER_UPDATED',req.user.sub,null,{userId:target.id,employeeId:target.employee_id});res.json({user:safeUser(userById(target.id))});}));
router.delete('/users/:id', requireAuth, roles('ADMIN','MASTER_ADMIN'), asyncHandler((req,res)=>{const target=userById(req.params.id);if(!target)throw new AppError(404,'User not found.');protectMaster(target);if(db.prepare('SELECT count(*) count FROM test_records WHERE operator_id=?').get(target.id).count)throw new AppError(409,'Users with field-test records cannot be removed. Suspend the account instead.');db.prepare('DELETE FROM audit_logs WHERE actor_user_id=?').run(target.id);db.prepare('DELETE FROM users WHERE id=?').run(target.id);audit('USER_REMOVED',req.user.sub,null,{userId:target.id,employeeId:target.employee_id});res.json({removed:true});}));
router.get('/audit-activity', requireAuth, roles('ADMIN', 'MASTER_ADMIN'), (req, res) => { const where=[],params=[],search=String(req.query.search||'').trim(),actionType=String(req.query.actionType||'ALL'),actorId=String(req.query.actor||''),range=String(req.query.range||'ALL'); if(search){const like=`%${search}%`;where.push('(u.full_name LIKE ? OR t.test_number LIKE ? OR a.action LIKE ?)');params.push(like,like,like);} const actionFilters={AUTHENTICATION:"a.action LIKE 'LOGIN_%'",FIELD_TEST:"(a.action LIKE 'FIELD_TEST_%' OR a.action LIKE 'TEST_%')",INTEGRITY:"(a.action LIKE '%INTEGRITY%' OR a.action IN ('HASH_MISMATCH','SIGNATURE_INVALID'))",ANALYSIS:"a.action='ANALYSIS_RERUN'",LAB_REVIEW:"a.action='LAB_REVIEW_REQUESTED'",REPORTS:"a.action LIKE 'REPORT_%'"};if(actionFilters[actionType])where.push(actionFilters[actionType]);if(actorId){where.push('a.actor_user_id=?');params.push(actorId);}if(range==='TODAY')where.push("date(a.created_at)=date('now')");if(range==='D7')where.push("a.created_at>=datetime('now','-7 days')");if(range==='D30')where.push("a.created_at>=datetime('now','-30 days')");const clause=where.length?`WHERE ${where.join(' AND ')}`:'';const events=db.prepare(`SELECT a.*,u.full_name actor_name,u.role actor_role,t.test_number FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_user_id LEFT JOIN test_records t ON t.id=a.test_record_id ${clause} ORDER BY a.created_at DESC LIMIT 200`).all(...params);const summary=db.prepare(`SELECT sum(CASE WHEN date(a.created_at)=date('now') THEN 1 ELSE 0 END) eventsToday,sum(CASE WHEN a.action LIKE 'FIELD_TEST_%' OR a.action LIKE 'TEST_%' THEN 1 ELSE 0 END) fieldTestEvents,sum(CASE WHEN a.action LIKE '%INTEGRITY%' OR a.action IN ('HASH_MISMATCH','SIGNATURE_INVALID') THEN 1 ELSE 0 END) integrityEvents,sum(CASE WHEN a.action='LAB_REVIEW_REQUESTED' OR a.action LIKE 'REPORT_%' THEN 1 ELSE 0 END) reviewReportEvents FROM audit_logs a`).get();const actors=db.prepare('SELECT id,full_name,role FROM users ORDER BY full_name').all();res.json({events,summary:{eventsToday:summary.eventsToday||0,fieldTestEvents:summary.fieldTestEvents||0,integrityEvents:summary.integrityEvents||0,reviewReportEvents:summary.reviewReportEvents||0},actors}); });
module.exports = router;
